# Door & Window States Package #

## This package shows the state of those windows in my house and the icon changes depending on whether they are open closed. ##

sensor:
###################################################
## Basement Window Open/Closed Front-end Sensor? ##
###################################################
  - platform: template
    sensors:
      basement_window_state:
        friendly_name: "Basement Window is Open/Closed?"
        value_template: >-
          {% if is_state('binary_sensor.basement_window_binary_sensor', 'on') %}
            Open
          {% else %}
            Closed
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.basement_window_binary_sensor', 'on') %}
            mdi:window-open-variant
          {% else %}
            mdi:window-closed-variant
          {% endif %}
###################################################
## Office Window Open/Closed Front-end Sensor? ##
###################################################
  - platform: template
    sensors:
      office_window_state:
        friendly_name: "Office Window is Open/Closed?"
        value_template: >-
          {% if is_state('binary_sensor.office_window_binary_sensor', 'on') %}
            Open
          {% else %}
            Closed
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.office_window_binary_sensor', 'on') %}
            mdi:window-open-variant
          {% else %}
            mdi:window-closed-variant
          {% endif %}
###################################################
## Office Door Open/Closed Front-end Sensor? ##
###################################################
  - platform: template
    sensors:
      office_door_state:
        friendly_name: "Office Door is Open/Closed?"
        value_template: >-
          {% if is_state('binary_sensor.office_door_binary_sensor', 'on') %}
            Open
          {% else %}
            Closed
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.office_door_binary_sensor', 'on') %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}

# ##################
#   - platform: template
#     sensors:
#       catheter_state_lastchanged:
#         friendly_name: "Your Catheter Was Turned"
#         value_template: >
#           {% set values = [
#             states.sensor.catheter_state.last_changed,
#             states.sensor.catheter_tap_google_sheets_raw_input.last_changed ] %}
#           {{ values | min }}
#         device_class: timestamp


# Medication Package #

## This package contains various information about my medication, tracking things like number of doses in the current 24 hours or over other time period amongst  many other metrics. ##

# sensor:
# # How Medication Medication doses today? #
#   - platform: command_line
#     name: "Number of Doses"
#     json_attributes:
#       - "range"
#       - "majorDimension"
#       - "values"
#     command: "/usr/bin/curl -X GET 'https://sheets.googleapis.com/v4/spreadsheets/1L3MaDf75XgAs6OhWFBgduCttRQPsHHI9JTjlFqAEmkc/values/Cleanapalooza_Analysis!D2?key=AIzaSyDTcHMelSeHAyY5MvXHKUvR7lV50lPo_Qg'"
#     value_template: >-
#       {{value_json['values'] | regex_findall_index(find='\d+')}}
#     scan_interval: 30
# # How Medication Medication Remaining today?
#   - platform: command_line
#     name: "Number of Doses Remaining"
#     json_attributes:
#       - "range"
#       - "majorDimension"
#       - "values"
#     command: "/usr/bin/curl -X GET 'https://sheets.googleapis.com/v4/spreadsheets/1L3MaDf75XgAs6OhWFBgduCttRQPsHHI9JTjlFqAEmkc/values/Cleanapalooza_Analysis!E2?key=AIzaSyDTcHMelSeHAyY5MvXHKUvR7lV50lPo_Qg'"
#     value_template: >-
#       {{value_json['values'] | regex_findall_index(find='\d+')}}
#     scan_interval: 30