# One-Time Password (OTP) Sensor #

## The otp sensor generates One-Time Passwords according to RFC6238 that is compatible with most OTP generators available, including Google Authenticator. You can use this when building custom security solutions and want to use “rolling codes”, that change every 30 seconds. https://www.home-assistant.io/integrations/otp/ ##

# Example configuration.yaml entry
sensor:
  - platform: otp
    name: !secret otp_name_00
    token: !secret otp_token_00
  - platform: otp
    name: !secret otp_name_01
    token: !secret otp_token_01
  - platform: otp
    name: !secret otp_name_02
    token: !secret otp_token_02
  - platform: otp
    name: !secret otp_name_03
    token: !secret otp_token_03
  - platform: otp
    name: !secret otp_name_04
    token: !secret otp_token_04
